name: check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run check
